#!/bin/sh
for FILE in $( find ${PWD} -depth 1 -not -name $( basename $0 ) -not -name '.*' -not -name 'README*' )
do
	rm -rf ${HOME}/.$( basename ${FILE} )

	# -s = symlink
	ln -s ${FILE} ${HOME}/.$( basename ${FILE} )
done

git submodule init
git submodule update
