#!/bin/sh
for FILE in $( find ${PWD} -maxdepth 1 -not -name $( basename $0 ) -not -name '.*' -not -name 'README*' )
do
	rm -rf ${HOME}/.$( basename ${FILE} )

	# -s = symlink
	ln -s ${FILE} ${HOME}/.$( basename ${FILE} )
done

git submodule update --init

VERSION=1
crontab 2>/dev/null -l | grep --quiet auto-update-dotfiles:${VERSION}
if [ $? -gt 0 ]
then
	echo "Installing crontab entry"
	( crontab -l ; echo "1 * * * * cd $( readlink -f $PWD ) && git pull # auto-update-dotfiles:${VERSION}" ) | crontab -
fi
